---
title: "Group Project 2: Formal Analysis"
output: html_document
date: "2024-03-10"
---

```{r}
library(MASS)
```


# Data Processing

```{r}
Animal <- read.csv("dataset16.csv")

Animal$year <- as.factor(Animal$year)
Animal$season <- ifelse(Animal$month %in% c(12, 1, 2), "Winter", Animal$month)
Animal$season <- ifelse(Animal$season %in% c(3, 4, 5), "Spring", Animal$season)
Animal$season <- ifelse(Animal$season %in% c(6, 7, 8), "Summer", Animal$season)
Animal$season <- ifelse(Animal$season %in% c(9, 10, 11), "Fall", Animal$season)
Animal$chip_status <- ifelse(Animal$chip_status == "SCAN CHIP", "Chip", "No Chip")
Animal <- subset(Animal, animal_type %in% c("CAT", "DOG"))
Animal$time <- Animal$month
Animal$time <- ifelse(Animal$year == 2017, Animal$month + 12, Animal$month)
```


# Poisson Model Fitting

```{r}
# Full Model
poisson_model1 <- glm(time_at_shelter ~ animal_type + year + intake_type + outcome_type + chip_status + month, family = poisson, data = Animal)
summary(poisson_model1)
```

```{r}
# Remove `animal_type`
poisson_model2 <- glm(time_at_shelter ~ year + intake_type + outcome_type + chip_status + month, family = poisson, data = Animal)
summary(poisson_model2)
```

```{r}
# Include `time`
poisson_model3 <- glm(time_at_shelter ~ animal_type + intake_type + outcome_type + chip_status + time, family = poisson, data = Animal)
summary(poisson_model3)
```

```{r}
# Remove `animal_type`
poisson_model4 <- glm(time_at_shelter ~ intake_type + outcome_type + chip_status + time, family = poisson, data = Animal)
summary(poisson_model4)
```

```{r}
# Step Selection for Final Model
null.model <- glm(time_at_shelter ~ 1, family = poisson, data = Animal)
step.model <- step(null.model,scope = list(lower = null.model, upper = poisson_model3), direction = "both")
summary(step.model)
```

```{r}
# Check Assumptions
residuals <- residuals(poisson_model4)

plot(poisson_model4, which = 1)
plot(poisson_model4, which = 2)
```

```{r}
# Distribution Assumption
mean(Animal$time_at_shelter)
var(Animal$time_at_shelter)
```


# Negative-Binomial Model Fitting

```{r}
# Full Model
negbin_model1 <- glm.nb(time_at_shelter ~ animal_type + intake_type + outcome_type + chip_status + year + month, data = Animal)
summary(negbin_model1)
```

```{r}
# Use `season` to replace `month`
negbin_model2 <- glm.nb(time_at_shelter ~ animal_type + intake_type + outcome_type + chip_status + year + season, data = Animal)
summary(negbin_model2)
```

```{r}
# Use `time` to replace `year` & `season`
negbin_model3 <- glm.nb(time_at_shelter ~ animal_type + intake_type + outcome_type + chip_status + time, data = Animal)
summary(negbin_model3)
```


```{r}
# Remove `animal_type`
negbin_model4 <- glm.nb(time_at_shelter ~ intake_type + outcome_type + chip_status + time, data = Animal)
summary(negbin_model4)
```

```{r}
# Step Selection for Final Model
null.model <- glm.nb(time_at_shelter ~ 1, data = Animal)
step.model <- step(null.model, scope = list(lower = null.model, upper = negbin_model3), direction = "both")
summary(step.model)
```

```{r}
# Check Assumptions
residuals <- residuals(negbin_model4)

plot(negbin_model4, which = 1)
plot(negbin_model4, which = 2)
```











