---
title: "Group 16"
format: html
editor: visual
---

```{r}
library(dplyr)
```

```{r}
Animal <- read.csv(file = "dataset16.csv")
```

```{r}
Animal$year <- as.factor(Animal$year)
Animal$season <- ifelse(Animal$month %in% c(12, 1, 2), "Winter", Animal$month)
Animal$season <- ifelse(Animal$season %in% c(3, 4, 5), "Spring", Animal$season)
Animal$season <- ifelse(Animal$season %in% c(6, 7, 8), "Summer", Animal$season)
Animal$season <- ifelse(Animal$season %in% c(9, 10, 11), "Fall", Animal$season)
Animal$intake_type <- ifelse(Animal$intake_type == "STRAY", "Stray", "From Owner")
Animal$outcome_type <- ifelse(Animal$outcome_type %in% c("DIED", "EUTHANIZED"), "Dead", "Rehomed")
Animal$chip_status <- ifelse(Animal$chip_status == "SCAN CHIP", "Chip", "No Chip")
Animal <- subset(Animal, animal_type %in% c("CAT", "DOG"))
```

# EDA

```{r}
library(ggplot2)
ggplot(data = Animal, aes(x = animal_type, y = time_at_shelter, fill = animal_type))+
  geom_boxplot()+
  labs(x = "animal_type", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. animal_type")
```

```{r}
ggplot(data = Animal, aes(x = season, y = time_at_shelter, fill = season))+
  geom_boxplot()+
  labs(x = "season", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. season")
```

```{r}
ggplot(data = Animal, aes(x = year, y = time_at_shelter, fill = year))+
  geom_boxplot()+
  labs(x = "year", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. year")
```

```{r}
ggplot(data = Animal, aes(x = intake_type, y = time_at_shelter, fill = intake_type))+
  geom_boxplot()+
  labs(x = "intake_type", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. intake_type")
```

```{r}
ggplot(data = Animal, aes(x = outcome_type, y = time_at_shelter, fill = outcome_type))+
  geom_boxplot()+
  labs(x = "outcome_type", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. outcome_type")
```

```{r}
ggplot(data = Animal, aes(x = chip_status, y = time_at_shelter, fill = chip_status))+
  geom_boxplot()+
  labs(x = "chip_status", y = "time_at_shelter")+
  theme(legend.position = "none")+
  ggtitle("boxplot of time_at_shelter vs. chip_status")
```

```{r}
ggplot(Animal, aes(x=time_at_shelter)) + 
  geom_density() +
  labs(title="Density Plot of Time at Shelter",
       x="Time at Shelter",
       y="Density")
```

```{r}
ggplot(Animal, aes(x = outcome_type, y = time_at_shelter, fill = animal_type, colour = animal_type)) + 
  geom_bar(stat = "identity")
```
